using System.Text;
using Keystone.Cli.Application.FileSystem;
using Keystone.Cli.Application.Utility.Serialization;
using Keystone.Cli.Application.Utility.Serialization.Yaml;
using NSubstitute;


namespace Keystone.Cli.UnitTests.Application.Utility.Serialization;

[TestFixture, Parallelizable(ParallelScope.All)]
public class YamlFileSerializerTests
{
    /// <summary>
    /// A sample YAML content used for testing purposes. This is a typical <c>pandoc.yaml</c> file
    /// generated by the Keystone project when creating a new book. It includes various metadata fields
    /// such as title, author, date, language, description, and keywords.
    /// </summary>
    private const string TestYamlContent = """
        ---
        # Keystone-generated Pandoc metadata file
        # See: https://pandoc.org/MANUAL.html#variables for more details

        # The title of your book
        #
        # This is the main title of your book, which will appear on the cover and in metadata.
        # It should be a descriptive title that reflects the content of your book.
        #
        title: Hello World

        # The subtitle of your book
        #
        # This is an optional subtitle that provides additional context or information about your book.
        # It will appear on the cover and in metadata. Leave empty if you don't want a subtitle.
        #
        subtitle: The sample book using the Keystone project

        # The author of your book
        #
        # This is the name of the author or organization responsible for the book.
        # It will appear on the cover and in metadata. You can include multiple authors
        # by separating them with commas.
        #
        author: Knight Owl LLC

        # The date of your book
        #
        # This is the publication date of your book. It can be a specific date or a keyword.
        #
        # Accepted values:
        # - auto: Automatically set to the current date when building the book
        # - disabled: Do not include a date in the book
        # - any date representing text, e.g., March 30, 2025
        #
        date: auto

        # The language (culture) of your book
        #
        # This sets the main document language, affecting metadata, chapter names, hyphenation,
        # and language-specific behavior in LaTeX, EPUB, and HTML.
        #
        # Use standard culture codes, e.g., en, en-US, en-CA, uk, uk-UA, de, fr, etc.
        #
        lang: en-US

        # The footer copyright text
        #
        # This is the copyright text that will appear in the footer of your book.
        # It can be a specific text or a keyword.
        #
        # Accepted values:
        # - auto: Automatically set to the current year and author name
        # - disabled: Do not include a copyright in the footer
        # - any custom text, e.g., © 2025 Jane Doe. All Rights Reserved
        #
        footer-copyright: auto

        # A short description of your book
        #
        # This is a brief description of your book, which will be included in metadata.
        # It should be a concise summary of the book's content and purpose.
        # It can span multiple lines, but keep it short and to the point.
        #
        description: |
          This is a tribute to beginnings.
          In every language, in every framework, "Hello, world" is the first spark — the moment code speaks back.
          This sample book is your invitation to begin — to build something real, reproducible, and yours.

        # A list of keywords for your book
        #
        # This is a list of keywords or tags that describe the content of your book.
        # They will be included in metadata for indexing or cataloging purposes.
        # You can use any keywords that are relevant to your book.
        #
        keywords:
          - hello-world
          - keystone
          - book
        ...
        """;

    private static YamlFileSerializer Ctor(IFileSystemService? fileSystemService = null)
        => new(fileSystemService ?? Substitute.For<IFileSystemService>());

    [Test]
    public async Task LoadAsync_EmptyFile_ReturnsEmptyDictionaryAsync()
    {
        var fileSystemService = Substitute.For<IFileSystemService>();
        fileSystemService.OpenReadStream(Arg.Any<string>()).Returns(new MemoryStream());

        var sut = Ctor(fileSystemService);
        var actual = await sut.LoadAsync("test.yaml");

        Assert.That(actual, Is.Empty);
    }

    [Test]
    public async Task LoadAsync_ValidFile_ReturnsDeserializedDictionaryAsync()
    {
        const string path = "pandoc.yaml";

        var fileSystemService = Substitute.For<IFileSystemService>();
        var stream = new MemoryStream(Encoding.UTF8.GetBytes(TestYamlContent));
        fileSystemService.OpenReadStream(path).Returns(stream);

        var expected = new Dictionary<string, YamlValue>
        {
            ["title"] = new YamlScalar("Hello World"),
            ["subtitle"] = new YamlScalar("The sample book using the Keystone project"),
            ["author"] = new YamlScalar("Knight Owl LLC"),
            ["date"] = new YamlScalar("auto"),
            ["lang"] = new YamlScalar("en-US"),
            ["footer-copyright"] = new YamlScalar("auto"),
            ["description"] = new YamlScalar(
                """
                This is a tribute to beginnings.
                In every language, in every framework, "Hello, world" is the first spark — the moment code speaks back.
                This sample book is your invitation to begin — to build something real, reproducible, and yours.
                """
            ),
            ["keywords"] = new YamlArray(["hello-world", "keystone", "book"]),
        };

        var sut = Ctor(fileSystemService);
        var actual = await sut.LoadAsync(path);

        Assert.That(actual, Is.EquivalentTo(expected).IgnoreWhiteSpace);
    }

    [Test]
    public async Task LoadAsync_IgnoresNestedStructuresAsync()
    {
        const string path = "test.yaml";
        const string yamlContent = """
            ---
            key1: value1
            key2:
              - item1
              - item2
            key3:
              subkey1: subvalue1
              subkey2: subvalue2
            key4: |-
              This is a multi-line
              scalar value.
            ...
            """;

        var fileSystemService = Substitute.For<IFileSystemService>();
        var stream = new MemoryStream(Encoding.UTF8.GetBytes(yamlContent));
        fileSystemService.OpenReadStream(path).Returns(stream);

        // ignores key3 with nested mappings
        var expected = new Dictionary<string, YamlValue>
        {
            ["key1"] = new YamlScalar("value1"),
            ["key2"] = new YamlArray(["item1", "item2"]),
            ["key4"] = new YamlScalar(
                """
                This is a multi-line
                scalar value.
                """
            ),
        };

        var sut = Ctor(fileSystemService);
        var actual = await sut.LoadAsync(path);

        Assert.That(actual, Is.EquivalentTo(expected).IgnoreWhiteSpace);
    }

    [Test]
    public async Task LoadAsync_RecognizesAlternativeFormattedYamlAsync()
    {
        const string path = "test.yaml";

        // ReSharper disable once StringLiteralTypo
        const string yamlContent = """
            ---
            key1: "value1"
            key2: ["item1", "item2"]
            key3: "This is a multi-line\nscalar value."
            ...
            """;

        var fileSystemService = Substitute.For<IFileSystemService>();
        var stream = new MemoryStream(Encoding.UTF8.GetBytes(yamlContent));
        fileSystemService.OpenReadStream(path).Returns(stream);

        var expected = new Dictionary<string, YamlValue>
        {
            ["key1"] = new YamlScalar("value1"),
            ["key2"] = new YamlArray(["item1", "item2"]),
            ["key3"] = new YamlScalar(
                """
                This is a multi-line
                scalar value.
                """
            ),
        };

        var sut = Ctor(fileSystemService);
        var actual = await sut.LoadAsync(path);

        Assert.That(actual, Is.EquivalentTo(expected).IgnoreWhiteSpace);
    }

    [Test]
    public async Task SaveAsync_WritesUpdatesWithPreservedStructureAsync()
    {
        const string path = "pandoc.yaml";

        var fileSystemService = Substitute.For<IFileSystemService>();
        await using var captureStream = new CapturingStream().SetContent(TestYamlContent);
        fileSystemService.OpenWriteStream(path).Returns(captureStream);

        var data = new Dictionary<string, YamlValue>
        {
            ["title"] = new YamlScalar("Hello World!"),
            ["subtitle"] = new YamlScalar("The updated sample book using the Keystone project"),
            ["author"] = new YamlScalar("Knight Owl LLC"),
            ["date"] = new YamlScalar("September, 2025"),
            ["lang"] = new YamlScalar("en-US"),
            ["footer-copyright"] = new YamlScalar("© 2025 Knight Owl LLC. All Rights Reserved"),
            ["description"] = new YamlScalar(
                """
                This is a tribute to beginnings.
                In every language, in every framework, "Hello, world" is the first spark — the moment code speaks back.
                This sample book is your invitation to begin — to build something real, reproducible, and yours.
                This is an extra line.
                """
            ),
            ["keywords"] = new YamlArray(["hello-world", "keystone", "book", "updated"]),
        };

        const string expected = """
            ---
            # Keystone-generated Pandoc metadata file
            # See: https://pandoc.org/MANUAL.html#variables for more details

            # The title of your book
            #
            # This is the main title of your book, which will appear on the cover and in metadata.
            # It should be a descriptive title that reflects the content of your book.
            #
            title: Hello World!

            # The subtitle of your book
            #
            # This is an optional subtitle that provides additional context or information about your book.
            # It will appear on the cover and in metadata. Leave empty if you don't want a subtitle.
            #
            subtitle: The updated sample book using the Keystone project

            # The author of your book
            #
            # This is the name of the author or organization responsible for the book.
            # It will appear on the cover and in metadata. You can include multiple authors
            # by separating them with commas.
            #
            author: Knight Owl LLC

            # The date of your book
            #
            # This is the publication date of your book. It can be a specific date or a keyword.
            #
            # Accepted values:
            # - auto: Automatically set to the current date when building the book
            # - disabled: Do not include a date in the book
            # - any date representing text, e.g., March 30, 2025
            #
            date: September, 2025

            # The language (culture) of your book
            #
            # This sets the main document language, affecting metadata, chapter names, hyphenation,
            # and language-specific behavior in LaTeX, EPUB, and HTML.
            #
            # Use standard culture codes, e.g., en, en-US, en-CA, uk, uk-UA, de, fr, etc.
            #
            lang: en-US

            # The footer copyright text
            #
            # This is the copyright text that will appear in the footer of your book.
            # It can be a specific text or a keyword.
            #
            # Accepted values:
            # - auto: Automatically set to the current year and author name
            # - disabled: Do not include a copyright in the footer
            # - any custom text, e.g., © 2025 Jane Doe. All Rights Reserved
            #
            footer-copyright: © 2025 Knight Owl LLC. All Rights Reserved

            # A short description of your book
            #
            # This is a brief description of your book, which will be included in metadata.
            # It should be a concise summary of the book's content and purpose.
            # It can span multiple lines, but keep it short and to the point.
            #
            description: |-
              This is a tribute to beginnings.
              In every language, in every framework, "Hello, world" is the first spark — the moment code speaks back.
              This sample book is your invitation to begin — to build something real, reproducible, and yours.
              This is an extra line.

            # A list of keywords for your book
            #
            # This is a list of keywords or tags that describe the content of your book.
            # They will be included in metadata for indexing or cataloging purposes.
            # You can use any keywords that are relevant to your book.
            #
            keywords:
              - hello-world
              - keystone
              - book
              - updated
            ...
            """;

        var sut = Ctor(fileSystemService);

        await sut.SaveAsync(path, data);
        var actual = captureStream.GetCapturedString();

        Assert.That(actual, Is.EqualTo(expected).IgnoreWhiteSpace);
    }

    [Test]
    public async Task SaveAsync_RoundTrip_PreservesOriginalContentAsync()
    {
        const string path = "pandoc.yaml";

        var fileSystemService = Substitute.For<IFileSystemService>();
        var originalStream = new MemoryStream(Encoding.UTF8.GetBytes(TestYamlContent));
        fileSystemService.OpenReadStream(path).Returns(originalStream);

        await using var captureStream = new CapturingStream().SetContent(TestYamlContent);
        fileSystemService.OpenWriteStream(path).Returns(captureStream);

        var sut = Ctor(fileSystemService);

        var loaded = await sut.LoadAsync(path);
        await sut.SaveAsync(path, loaded);
        var savedContent = captureStream.GetCapturedString();

        Assert.That(savedContent, Is.EqualTo(TestYamlContent).IgnoreWhiteSpace);
    }

    [Test]
    public async Task SaveAsync_AddsNewKey_BeforeTerminatorAsync()
    {
        const string path = "test.yaml";
        const string initialYaml = """
            ---
            key1: value1
            ...
            """;

        var fileSystemService = Substitute.For<IFileSystemService>();
        await using var captureStream = new CapturingStream().SetContent(initialYaml);
        fileSystemService.OpenWriteStream(path).Returns(captureStream);

        var data = new Dictionary<string, YamlValue>
        {
            ["key1"] = new YamlScalar("value1"),
            ["new-key"] = new YamlScalar("new-value"),
        };

        const string expectedYaml = """
            ---
            key1: value1
            new-key: new-value
            ...
            """;

        var sut = Ctor(fileSystemService);

        await sut.SaveAsync(path, data);
        var actual = captureStream.GetCapturedString();

        Assert.That(actual, Is.EqualTo(expectedYaml).IgnoreWhiteSpace);
    }

    [Test]
    public async Task SaveAsync_AddsNewKey_AtEnd_WhenNoTerminatorAsync()
    {
        const string path = "test.yaml";
        const string initialYaml = """
            ---
            key1: value1
            """;

        var fileSystemService = Substitute.For<IFileSystemService>();
        await using var captureStream = new CapturingStream().SetContent(initialYaml);
        fileSystemService.OpenWriteStream(path).Returns(captureStream);

        var data = new Dictionary<string, YamlValue>
        {
            ["key1"] = new YamlScalar("value1"),
            ["new-key"] = new YamlScalar("new-value"),
        };

        const string expectedYaml = """
            ---
            key1: value1
            new-key: new-value
            """;

        var sut = Ctor(fileSystemService);

        await sut.SaveAsync(path, data);
        var actual = captureStream.GetCapturedString();

        Assert.That(actual, Is.EqualTo(expectedYaml).IgnoreWhiteSpace);
    }
}
